# Foundations

We begin with some foundational material that forms the basis of all applied mathematics.

## Numbers

We deal with various number systems in mathematics.

* The set of *natural numbers* are the familiar counting numbers:
    $$1, 2, 3,\dotsc$$
    We denote these by the symbol $\mathbb{N}$.

* The *integers* are the "whole numbers", which include zero and negative numbers:
    $$\dots,-2,-1,0,1,2,\dots$$
    We denote these by the symbol $\mathbb{Z}$.

* We sometimes want to focus on just the *positive integers*, which is another name for the natural numbers.

* The *non-negative integers* are the numbers:
    $$0, 1, 2, 3,\dotsc$$
    (the natural numbers and zero).

* The *negative integers* are the numbers:
    $$-1, -2, -3,\dotsc$$

* The *rational numbers* are numbers which can be written in the form $\frac{a}{b}$ where $a$ and $b$ are integers, with $b\neq 0$, so numbers like
    $$\frac{1}{2}, \frac{3}{2}, -\frac{4}{5}, \dotsc$$
    Note these include the integers since they can be written as $\frac{a}{1}$. Rational numbers are denoted $\mathbb{Q}$.

* The ancient Greeks discovered that there are numbers that are not rational -- so-called *irrational numbers*. For example, $\sqrt{2}, \pi$ and $e$ are all irrational numbers. One way of characterising irrational numbers is that they have a decimal representation that never repeats...
    $$
    \pi=3.141592653589793238462643383279502884197169399375105820\dots
    $$
    In contrast, all rational numbers have an eventually repeating decimal expansion (after perhaps some initial jumble of digits, there is a repeating pattern), for example:
    
    |Rational Number| Repeating pattern|
    |---|---|
    |$\frac{1}{3}=0.333\dots$|repeating $3$|
    |$\frac{3}{2}=1.5000\dots$|repeating $0$ after the first decimal digit, which we normally don't write down!|
    |$\frac{219}{1750}=0.125142857142857\dots$|repeating sequence $142857$ of length $6$ after the first $3$ decimal digits|    

* The *real numbers* consist of all rational and irrational numbers together. We can think of real numbers as points on a continuous straight line, or as numbers that possibly have a decimal representation requiring an infinite number of digits^[Real numbers require quite a bit of work to define in a rigorous mathematical way and we will not do this here; the interested reader should look up "construction of real numbers by Dedekind cuts" or "construction of real numbers by Cauchy sequences".].
    The set of real numbers is denoted by $\mathbb{R}$.

* We learn about all of the above numbers early on in our mathematical education. However, there is a further set of numbers that is very useful in science and engineering that you may not have encountered before: the *complex numbers*, denoted by $\mathbb{C}$. These are not as intuitive as real numbers and they are explored in section \@ref(complex).


## Algebra

Algebra is the general name given to the rules for manipulating numerical variables.

We often use letters as placeholders for numerical values. We can then manipulate these letters as if they were numbers using the rules of algebra, re-arranging formulae, or finding the general solution to an equation. We can then "plug-in" specific numbers to get the answer.

Being fluent in the notation and manipulations of algebra allows us to progress to higher (more useful and more interesting) areas of mathematics.

### BEDMAS

Recall that when an expression contains multiple arithmetic operations, there is a certain *precedence* (they must be carried out in a certain order), so that there is no ambiguity in evaluating the answer. This is usually remembered by the acronym BEDMAS:

B - Brackets

E - Exponents

D - Division

M - Multiplication

A - Addition

S - Subtraction

Division and Multiplication can be carried out in either order, as can Addition and Subtraction. We'll recap the rules of Brackets and Exponents in the next sections.

::: {.example name="BEDMAS" #BEDMAS}
We have
$$3+2\times 4=11,$$
whilst
$$(3+2)\times 4 = 20.$$
Another example:
$$18\div 3^2 = 2$$
whilst
$$(18\div 3)^2 = 36.$$ 
:::

### Notation for Multiplication and Division

Let $a,b$ and $c$ be numerical variables.

To simplify our mathematical writing, we shorten the multiplication $a\times b$ to $ab$

We also write division $a\div c$ in the "fraction" form $\dfrac{a}{c}$

Since division and multiplication can be carried out in either order, the following are different ways of writing the same thing:
$$\dfrac{a}{c}b=\dfrac{ab}{c}=a\dfrac{b}{c}$$

and since multiplication of two numbers can be carried out in either order, there are even more ways of writing this expression:
$$\frac{b}{c}a=\frac{ba}{c}=b\frac{a}{c}$$

### Rules of Exponents {#exponents}

In their most basic form, we use exponents as a shorthand for multiplication of a number by itself a given number of times. For example:

$5\times 5 = 5^2$ spoken as "5 squared" or "5 to the power 2"

$5\times 5\times 5=5^3$ spoken as "5 cubed" or "5 to the power 3"

and more generally, for any numbers $x$ and $a$,

$\underbrace{x\times \dotsb \times x}_{\text{with }a\, x\text{'s}} = x^a$ spoken as "x to the power $a$"

In the expression $x^n$, the number $x$ is known as the *base* and the number $n$ is known as the *power*, *index* or *exponent*.

Next, we look at rules for combining and simplifying exponents. We start by assuming the base $x$ is a positive real number and the exponent $a$ is a postive integer.

Now for any positive integers $a$ and $b$, it should be clear that the following rule holds:

::: {.theorem #exprule1 name="Rule 1"}
Multiplying powers with the same base:
$$x^ax^b=x^{a+b}$$
:::

since we are multiplying together $a$ lots of $x$ by a further $b$ lots of $x$ to give a total of $a+b$ lots of $x$ multiplied together

$$\underbrace{x\times \dotsb \times x}_{\text{with }a\, x\text{'s}}\times\underbrace{x\times \dotsb \times x}_{\text{with }b\, x\text{'s}}=\underbrace{x^{a+b}}_{\text{with }a+b\, x\text{'s}}$$

::: {.example name="Multiplying powers"}
Example:

$2^3 2^4 = 2^7$

It is also worth seeing a non-example:

$3^3 4^2=?$

<!-- Felt statement pre-edit was a bit misleading, e.g., you could decompose into prime factors then combine exponents of like factors -->
Here:

$$3^3 4^2=(3\times 3 \times 3) \times (4 \times 4) = 27 \times 16=432$$

and this number cannot be written as a power of any whole number.
:::

Extending this idea, we also have:

::: {.theorem #exprule2 name="Rule 2"}
Power of a Power
$$(x^a)^b=x^{ab}$$
:::

This follows from Rule 1 since
$$(x^a)^b=\underbrace{x^a\times \dotsb \times x^a}_{b\, \text{times}}=x^{a+\dotsb+a}=x^{ab}$$

::: {.example name="Power of a power"}
$(5^3)^4=5^{12}$
:::

::: {.exercise #rule2}
Show that $(x^a)^b=(x^b)^a$.
:::

The following is a straightforward rule applying when we have powers of products of two different numbers $x$ and $y$.

::: {.theorem #exprule3 name="Rule 3"}
Power of a product:
$$(xy)^a=x^ay^a$$
:::

::: {.example name="Power of a product"}
$(2\times 3)^4=(2\times 3)\times(2\times 3)\times(2\times 3)\times(2\times 3)
= 2^4\times 3^4$
:::

And we have a similar rule for powers of quotients.

::: {.theorem name="Rule 4"}
Power of a quotient:

$$\left(\frac{x}{y}\right)^a=\frac{x^a}{y^a}$$
:::

This follows from the previous rule:

$\left(\frac{x}{y}\right)^a=\left(x\frac{1}{y}\right)^a=x^a\left(\frac{1}{y}\right)^a=x^a\frac{1}{y^a}=\frac{x^a}{y^a}.$

So far we have allowed the exponents to be positive integers. Can we make sense of negative integers as exponents? Consider, for $a$ and $b$ as positive integers, the product

$$x^a\frac{1}{x^b}=\frac{x^a}{x^b}$$

Let's start with a concrete example and for arguments sake let's take $a>b$ with $a=5, b=2$. Then:

$$\frac{x^5}{x^2}=\frac{x\times x \times x\times x \times x}{x \times x}=x\times x\times x=x^3$$

where we have cancelled the 2 common factors of $x$, leaving us with a product of $5-2=3$ lots of $x$.

More generally, taking $\frac{x^a}{x^b}$ for $a>b$ we have $a$ lots of $x$ on the top and $b$ lots of $x$ on the bottom, so we can cancel the common factors to leave $a-b$ lots of $x$. So,

\begin{equation}
\frac{x^a}{x^b}=x^{a-b} (\#eq:divexps)
\end{equation}

<!-- Figured reciprocal might be unfamiliar terminology -->
and following Rule 1 we could think of this as $x^{a-b}=x^{a+(-b)}=x^ax^{-b}$. In particular, $x^{-b} = \frac{1}{x^b}$ (referred to as the reciprocal of $x^b$).

::: {.theorem #exprule3 name="Rule 5"}
$$x^{-a}=\frac{1}{x^a}$$
:::


::: {.example name="Negative Exponents"}
1. Note in particular $x^{-1}=\frac{1}{x}$, the reciprocal of $x$

2. Generally, $\frac{x^a}{x^b}=x^a\frac{1}{x^b}=x^ax^{-b}=x^{a-b}$

so, for example,

$$\frac{5^6}{5^2}=5^4$$

and

$$\frac{7^2}{7^5}=7^{-3}$$
(which is $\dfrac{1}{7^3}$)

3. How do negative exponents work in a "power of a power"?

$$(x^2)^{-3}=\frac{1}{(x^2)^{3}}=\frac{1}{x^6}=x^{-6}$$

which is compatible with the "multiply exponents" rule

$$(x^2)^{-3}=x^{(2\times -3)}=x^{-6}$$.
:::

<!-- Changed treatment of zero to the power of zero, following https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero -->
So far we have assumed $x$ is positive. What happens when $x=0$? Then $0^a$ is multiplying $0$ by itself $a$ times, so the result is obviously $0$. Note this does not hold when $-a<0$, since $0^{-a}=\frac{1}{0^a}=\frac{1}{0}$, which is an indeterminate form. The case in which $a = 0$, that is, $0^0$, is defined differently in different contexts (which is ok, providing it is clear which definition is being used and it is being used consistently). So we restrict to $a>0$ for this result.

::: {.theorem #exprule3 name="Rule 6"}
$$0^{a}=0, \text{ for }a>0$$
:::

Next, we can consider the exponent $a=0$, that is, the value of $x^0$. In \@ref(eq:divexps) with the particular case $b=a$, we have

$$1=\frac{x^a}{x^a}=x^{a-a}=x^0$$

<!-- Changed footnote on zero to the power of zero -->
so we get that for any non-zero^[Some consider that $0^0$ is an indeterminate form.] value of $x$:

::: {.theorem name="Rule 7"}
$$x^0=1, \text{ for } x\neq 0$$
:::

So far we have only considered exponents that are integers and values of the base that are non-negative real numbers. It turns out that the previous rules actually apply to any *real number* exponent and non-negative real number base. We'll start by thinking about *fractional exponents*, and in particular exponents of the form

$$x^{\frac{1}{a}}$$

where $a$ is a non-zero integer.

::: {.example }

Take $(9^\frac{1}{2})^2=9^{(\frac{1}{2}\times 2)}=9^1=9$.

This implies that $9^{\frac{1}{2}}=3$, the square root of $9$.
:::

More generally, take $(x^\frac{1}{a})^a=x^{\frac{1}{a}a}=x^1=x$. This means that raising $x^\frac{1}{a}$ to the power $a$ gets us back to $x$, hence the number $x^\frac{1}{a}$ is the $a^\text{th}$ root of $x$. In particular, the square root is $x^{\frac{1}{2}}=\sqrt{x}$ and the cube root is $x^{\frac{1}{3}}=\sqrt[3]{x}$; we tend to use the root notation for expressions containing square or cube roots on their own, and use the power notation when combining different roots.

::: {.theorem name="Rule 8"}

Reciprocal powers are roots:
$$x^\frac{1}{a}=\sqrt[a]{x}.$$
:::

::: {.example}

$8^\frac{1}{3}=\sqrt[3]{8}=2.$
:::

Now lets try to make sense of a power of the form $x^{\frac{a}{b}}$ where $a$ is an integer and $b$ is a positive integer. That is, we now allow for any fractional (otherwise known as *rational*) exponent. Since we have $\frac{a}{b}=a\frac{1}{b}$, we can write (using Rule 2):

$$x^{\frac{a}{b}}=x^{a\frac{1}{b}}=(x^a)^{\frac{1}{b}}=\sqrt[b]{x^a},$$

or, equivalently

$$x^{\frac{a}{b}}=x^{\frac{1}{b}a}=(x^{\frac{1}{b}})^a=(\sqrt[b]{x})^a.$$

::: {.theorem name="Rule 9"}
Fractional exponents:
$$x^{\frac{a}{b}}=\sqrt[b]{x^a}=(\sqrt[b]{x})^a.$$
:::

### More on exponents

As we mentioned, an exponent can be *any* real number. Not all numbers can be written as fractions i.e. *rational numbers*, such as $\sqrt{2}, \pi, e$: these are called *irrational numbers*, and the above rules still work with irrational exponents. Proving this is beyond the scope of these notes, but your calculator can happily handle calculations with any real number exponent.

Another thing we have not mentioned so far is what happens when $x$ is a negative number. This is easy to understand when the exponent $a$ is an integer, since we are just multiplying a negative number by itself multiple times (and taking the reciprocal if $a$ is negative). But how do we interpret something like $y=(-1)^\frac{1}{2}$? That is, $y$ must be a number such that when it is multiplied by itself it gives the negative number $-1$, but this is impossible for a real number! Answering this conundrum requires us to invent a new set of numbers, called *complex numbers* -- this is addressed in section \@ref(complex).

A summary of the rules:

::: {.theorem #exprules name="Rules of Exponents"}

1. $x^ax^b=x^{a+b}$
2. $(x^a)^b=x^{ab}$
3. $(xy)^a=x^ay^a$
4. $\left(\frac{x}{y}\right)^a=\frac{x^a}{y^a}$
5. $x^{-a}=\frac{1}{x^a}$
6. $0^a=0$, for $a>0$
7. $x^0=1$, for $x\neq 0$
8. $x^{\frac{1}{a}}=\sqrt[a]{x}$
9. $x^{\frac{a}{b}}=\sqrt[b]{x^a}=(\sqrt[b]{x})^a.$
:::


### Brackets

We use brackets to set the precedence (or order) of evaluating the different parts of an expression. We evaluate the innermost brackets first. Note we usually omit the multiplication sign when multiplying a bracketed expression.

::: {.example name="Evaluating brackets"}
$$5(((2+4)\div (5-2))+1)=5((6\div 3)+1)=5(2+1)=5\times 3 = 15.$$
:::

Sometimes you might find it helpful to add "redundant" brackets to make the calculation clearer. For example, we could write
$$3+2\times 4=11$$
as
$$3+(2\times 4)=11.$$
The brackets are not really needed in the second version since we get the same result from following BEDMAS, but adding brackets can make an expression easier to read and evaluate.

#### Expansion

Recall that we can expand expressions involving multiplication of brackets by multiplying each term, such as the following:

$$a(b+c)=ab+ac$$
$$(a+b)(c+d)=ac+ad+bc+bd$$
$$(a+b)^2=(a+b)(a+b)=a^2+ab+ba+b^2=a^2+b^2+2ab$$
$$(ab)^2=(ab)(ab)=abab=a^2b^2.$$

We often want to expand expressions in order to simplify them by grouping together like-terms, for example:

$$(a+b)(b+c)+2ac=ab+ac+b^2+bc+2ac=ab+3ac+b^2+bc.$$

With more than two brackets, we do the expansion in two steps: it does not matter which expansion we perform first. For example, we could start by expanding the first two sets of brackets in the following

<!-- Appearing cropped on laptop fullscreen so split into a multline: not sure if supported in RMarkdown -->
\begin{multline*}
\underbrace{(a+b)(c+d)}_{\text{first expand these two}}(e+f) \\
=(ac+ad+bc+bd)(e+f)\\
=ace+ade+bce+bde + acf+adf+bcf+bdf
\end{multline*}

but since the order of multiplication is unimportant, we could have started by expanding any two of the three sets of brackets.

<!-- Changed sentence ordering for readability -->
In the case of the sum of two numbers (a *binomial* term) to a postive integer power, i.e. something of the form

$$(a+b)^n, \quad \text{where } n \text{ is a positive integer},$$

we have a general formula for the expansion which involves multiplying out the brackets $n$ times. We start by looking at a slightly simpler form
$$(1+x)^n.$$

Let's take a look at the expansion for the first few values of $n$.

$n=0:$ $(1+x)^0 = 1$

$n=1:$ $(1+x)^1=1+x$

$n=2:$ $(1+x)^2=(1+x)(1+x)=x^2+2x+1$

$n=3:$ $(1+x)^3=(1+x)(1+x)^2=(1+x)(x^2+2x+1)=x^3+3x^2+3x+1.$

<!-- Suggested to remove this text as I think it could otherwise do with more info about what Pascal's triangle is, which is perhaps more than is required: The coefficients of $x$ form the $n^\text{th}$ row of Pascal's triangle. -->

The general formula is:

$$(1+x)^n = \binom{n}{0}x^0+\binom{n}{1}x^1+\binom{n}{2}x^2+\dotsb+\binom{n}{n-1}x^{n-1}+\binom{n}{n}x^n$$

where $\binom{n}{k}$ is the binomial coefficient

$$\binom{n}{k}=\frac{n!}{k!(n-k)!}$$

and $n!$ is the *factorial* of $n$:

$$n!=n\times(n-1)\times(n-2)\times\dotsb \times3\times 2\times 1.$$

Given the more general form $(a+b)^n$, we can first extract a factor of $a$ to give

$$(a+b)^n=(a(1+\frac{b}{a}))^n=a^n(1+\frac{b}{a})^n$$

so we now just need to evaluate $(1+\frac{b}{a})^n$ using the formula, and then substitute $x$ with $\frac{b}{a}$. Alternatively, the full formula is:

$$(x+y)^n = \binom{n}{0}x^ny^0+\binom{n}{1}x^{n-1}y^1+\binom{n}{2}x^{n-2}y^2+\dotsb+\binom{n}{n-1}x^1y^{n-1}\binom{n}{n}x^0y^n.$$

#### Factorisation

At other times, we wish to simplify by extracting common factors from an expression, which we call *factorisation*. In the simplest form, this could just be factorising a single number

$$2x+2y=2(x+y).$$

Or, it could involve extracting more complicated factors, for example

$$2xy+6x^2y=2xy(1+3x)$$
$$x^2-3x-10=(x+2)(x-5).$$

The second example here is *factorising a quadratic* which we can do systematically by finding the roots -- we will see how to do this later in section \@ref(quad-eqs).


### Simplifiying Expressions

In order to simplify an expression we can carry out the following proceedures:

* Expand brackets
* Collect together any like-terms, e.g. $2a+3b+a=3a+3b$, or $a^3a^2+b^2=a^5+b^2$
* Simplify any fractions: use common denominators, e.g. $\frac{a}{b}+\frac{c}{d}=\frac{da+bc}{bd}$;  cancel any common factors, e.g. $\frac{ab}{ac}=\frac{b}{c}$
* Factorise

Note: these are "rules of thumb", as there usually does not exist such a thing as a "simplest" form for a given algebraic expression. The meaning of "simple" is dependent on what we want to gain from it. The intention is to put the expression in a form that is easier to understand (in the given context) and which usually uses fewer symbols (but not always).


## Equations

An equation indicates the *equality* of two mathematical expressions: what is on the left of the $=$ sign is the same as what is on the right of the $=$ sign. When manipulating equations, we must perform the same operation to each side in order to maintain equality -- think about a traditional mechanical balance scale, where if we were to change the mass on one side of the balance we would need to do the same to the other side in order to maintain balance. We will use the abreviations l.h.s. for left-hand-side and r.h.s. for right-hand-side. There are a few subtly different types of equations; the main two are *formulas* and *conditional equations*.

### Formulas {#formulas}

Equations are often regarded as *formulas*, which can be used to calculate the value of a mathematical or physical quantity in terms of other known quantities. In this case, we write a single *dependent* variable on the left hand side and the right hand side will contain *independent* variables and constants. The value of the dependent variable *depends* on the values of the independent variables and is obtained by evaluating the right hand side when the values of the independent variables are known. For example, the formula for the area $A$ of a circle is

$$A=\pi r^2$$

where the independent variable $r$ is the radius of the cirle and $\pi$ is the mathematical constant $3.141...$. By plugging in a particular value for $r$ we then obtain a value for the area $A$.  We often want to re-arrange equations to make a different variable the dependent variable, or *subject*, of the formula, i.e. to place it alone on the left hand-side. Re-arranging formulae is also known as *transposition*. For example, if we knew the area of a circle and wanted to calculate the corresponding radius, we can re-arrange the equation to make $r$ the subject:

$$r=\sqrt{\frac{A}{\pi}}.$$

In obtaining this, we carry out the "opposite" of the operations on the right hand side to both sides of the equation. These opposites are:

* addition and subtraction;
* multiplication and division;
* powers and roots.

Let's see this step by step in our example. We start with 

$$A=\pi r^2.$$

Then, divide both sides by $\pi$

$$\frac{A}{\pi}=\frac{\pi}{\pi}r^2=r^2$$

so that $r^2$ is no longer multiplied by $\pi$. Now, to get from $r^2$ to $r$ we need to take the square root of both sides

$$\sqrt{\frac{A}{\pi}}=\sqrt{r^2}=r$$

and finally, we (typically) put the subject on the left hand side (For those who write from left to right, as in the English language, this is a natural convention. Mathematically, it makes no difference which way around the equation is written).

$$r=\sqrt{\frac{A}{\pi}}.$$

<!-- Some commentary on use of words dependent and independent, perhaps a bit elaborate! -->
We note that the use of the words dependent and independent variables can be a bit misleading as they can imply causation (i.e. it is the occurence or setting of the values of the independent variables that causes the dependent variable to take its value). As we have demonstrated in the circle example, we may take either the area or the radius of the circle as the independent variable. As a reflection on causality (and its appropriateness): Is it the radius of the circle that causes its area? or the area that causes the radius? Or do the two merely coexist? (In a perfect harmony?).

### Conditional equations

Another type of equation is a *conditional* equation. These may not hold true for all values of the variables and we will want to find the values for which equality is true. For example,
$$5x+4=19$$
is only true when $x=3$. We can solve this equation by making $x$ the subject:

subract $4$ from both sides

$$5x=15$$

divide both sides by $5$

$$x=3.$$

Note that an equation may have more than one solution, or perhaps no solutions. For example,

$$x^2=4$$

has two possible solutions, either $x=2$ or $x=-2$. On the other hand, the equation

$$x+2=x+3$$

has no solutions. To see this, subtract $x+2$ from both sides and we obtain

$$0=1$$

which is false, so no value of $x$ can give us equality.

## Inequalities

You may be familiar already with the symbols $<, \leq, >$ and $\geq$, (less than, less than or equal to, greater than and greater than or equal to). These are used to define inequalities.

::: {.example #ineqs}
$$x<5$$ denotes all numbers that are strictly less that $5$ (so not including $5$ itself).
$$-1< x \leq 1$$ denotes all numbers that are strictly greater than $-1$ but less that or equal to $1$ (so $x=1$ is a possibility).
:::

When re-arranging inequalities we need to be a bit more careful with their manipulation than with equalities. If we perform the same operation to both sides in an equality then the equality still holds true, but this is not the case in general for inequalities -- in particular we need to be careful with multiplication by negative numbers which "flips" the inequality.

For example, if we take all values $x$ such that $x>10$, then an equivalent expression after multiplying by $-1$ is $-x<-10$ (NOT $-x>-10$).

Let $a,u,v,x,y,z$ be real numbers, then some basic relations that hold true are:

* if $x>y$ and $y>z$, then $x>z$;
* if $x>y$, then $x+z>y+z$ and $x-z>y-z$;
* if $x>y$ and $u>v$, then $x+u>y+v$;
* if $x>y$, then $ax>ay$ if $a>0$, and $ax < ay$ if $a<0$;
* if $x>y$, then $\dfrac{x}{a}>\dfrac{y}{a}$ if $a>0$, and $\dfrac{x}{a}<\dfrac{y}{a}$ if $a<0$;
* if $x>y>0$ and $u>v>0$, then $xu>yv$ and $\dfrac{x}{v}>\dfrac{y}{u}$;
* if $x>y>0$, then $\dfrac{1}{x}<\dfrac{1}{y}$.

It should not be necessary to memorise all of these, it just requires a little thought when manipulating inequalities: the important ones to be careful with are multiplying or dividing by negative values.


## Common mistakes!

We finish this section with some common algebraic errors to watch out for! Invent your own examples to convince yourself that these things are true.

**Fractions:** $\frac{a}{b+c}\neq \frac{a}{b}+\frac{a}{c}$ and $\frac{a+b}{c+b}\neq\frac{a}{c}$ (can't "cancel" the $b$ terms.).

**Inequalities:** $ab>c$ does not imply that $a>\frac{c}{b}$ (what happens if $b$ is negative?).

**Powers:** $(a+b)^2\neq a^2+b^2$.

**Roots:** $\sqrt{a+b}\neq \sqrt{a}+\sqrt{b}$.
