--- 
title: "Introduction to Mathematics for Data Science"
author: "Drs Mark Callaway, Tim Hughes and Ed Branford"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo:  maths-sci-eng/maths-sci-eng.github.io 
description: "Mathematics Self Study Materials for University of Exeter in Cornwall"
---

# Preface {-}

These notes have been compiled for self study and to complement courses at the University of Exeter in Cornwall. They were originally developed for scientists and engineers and we are in the process of adding in examples from other application areas. 

They are a work in progress -- please get in touch if you find any errors or have any feedback.

Contact: <m.callaway@exeter.ac.uk>, <t.h.hughes@exeter.ac.uk>, <e.h.branford@exeter.ac.uk>.

Recommended text for chapters 1--21: [@Bird]. Available online through the University of Exeter library.


## Acknowledgements {-}

Thank you to our many colleagues who have contributed to these notes by sharing lecture materials, and especially to Dr TJ McKinley, Dr Houry Melkonian, Dr Markus Mueller and Prof Stuart Townley.

This book has been written in Rmarkdown using the [bookdown package](https://bookdown.org/yihui/rmarkdown/books.html). Thank you to the bookdown creator, Yihui Xie.


```{r, include=FALSE}
knitr::opts_chunk$set(
  comment = "#>", echo = FALSE, fig.align = 'center'
)
```